- package.json
- src/constants/index.ts
- src/hooks/useConnect.ts
- src/hooks/useManage.ts
- src/hooks/useRegister.ts
- src/pages/manage.tsx
- src/pages/register.tsx
- src/states/extension.ts
- src/types/index.ts
- yarn.lock
- Query more storage and constants value from Gemini-3g on connectWallet to improve UX
- Add option to stake Max available account balance (on registration and add fund)
- Add option to select the domain id from the current list of available domains
> Improve web3 components for the Register page

- src/components/operatorSelector.tsx
- src/hooks/useConnect.ts
- src/hooks/useManage.ts
- src/hooks/useOnchainData.ts
- src/hooks/useRegister.ts
- src/pages/manage.tsx
- src/states/manage.ts
- src/types/index.ts
- src/utils/index.ts
- Add a selector dropdown to select operatorId
- Add a max withdraw amount that reflect the current stake in the selected operator
- Use float number as amount input
> Improve operator id input

- src/components/buttons.tsx
- src/components/intro.tsx
- src/components/operatorsList.tsx
- src/components/operatorsTotal.tsx
- src/components/wallet.tsx
- src/constants/styles.ts
- src/pages/index.tsx
- src/pages/manage.tsx
- src/pages/register.tsx
- src/pages/stats.tsx
- Fix min width of connect button
- Reduce font size for totals in manage and stats
- Unify the style in one location for easy change and uniformity
> Improve style

- package.json
- src/components/operatorsList.tsx
- src/components/operatorsTotal.tsx
- src/hooks/useManage.ts
- src/hooks/useOnchainData.ts
- src/hooks/useTx.ts
- src/types/index.ts
- src/utils/index.ts
- Fix the mapping of operators (I had assumed the key in the array was the operatorId)
- Fix hex number parsing
- Add signing key column in the stats and manage table
> Fix operators list

- src/components/intro.tsx
- src/constants/index.ts
> fix external url

- src/components/operatorsList.tsx
> fix wrong operator account when selecting one

- src/constants/index.ts
- src/hooks/useManage.ts
- src/hooks/useRegister.ts
- src/pages/register.tsx
- src/states/manage.ts
- src/types/index.ts
> Improve UX

- src/components/operatorsList.tsx
- src/components/wallet.tsx
- Add wallet label in wallet dropdown
- Add wallet label next to your operator
> Add wallet label in wallets dropdown and in list

- src/components/layout.tsx
- src/components/operatorsList.tsx
- src/components/walletDetails.tsx
- src/constants/styles.ts
- src/pages/manage.tsx
- src/pages/operatorStats/[operatorOwner].tsx
- src/pages/stats.tsx
- Icons getting too big on large screen
- Switch to have the aggregated stats on top of operators list
- Fix the max width of the page to 1600px
> Fix a few small UI issues

- src/utils/index.ts
> Error when trying to register with more than 999 tSSC #41

- src/components/actions.tsx
- src/components/intro.tsx
- src/components/operatorsList.tsx
- src/components/operatorsTotal.tsx
- src/components/transactionsSpotter.tsx
- src/components/wallet.tsx
- src/components/walletDetails.tsx
- src/constants/index.ts
- src/hooks/useConnect.ts
- src/hooks/useManage.ts
- src/hooks/useOnchainData.ts
- src/hooks/useRegister.ts
- src/pages/register.tsx
- src/states/extension.ts
- src/types/index.ts
- src/utils/index.ts
> Use chain data for symbol, decimal and address format

- src/components/operatorsList.tsx
- src/constants/index.ts
- src/hooks/useRegister.ts
- src/pages/register.tsx
- src/states/manage.ts
- src/states/registration.ts
- src/utils/index.ts
> A few more UX improvements

- src/components/nominatorsList.tsx
- src/components/operatorsList.tsx
- src/components/operatorsTotal.tsx
- src/constants/index.ts
- src/hooks/useOnchainData.ts
- src/pages/nominators.tsx
- src/pages/nominatorsStats/[operatorId].tsx
- Add total nominators count in the table
- Add nominators page (for all nominators and focus on a operator id)
> Add nominators count on list

- .vscode/settings.json
- src/components/operatorsTotal.tsx
- src/components/transactionsSpotter.tsx
- src/constants/index.ts
- src/hooks/useOnchainData.ts
- src/hooks/useTx.tsx
- src/types/index.ts
- Add pending deposit to Funds in stake
- Remove some console log in useTx
- Improve transaction spotter to look at more blocks (and make it a constant)
- #39
> Add pendings details to UI

- src/components/operatorsTotal.tsx
> fix total nominator stake and operator stake

- src/components/nominatorsList.tsx
- src/components/operatorsCards.tsx
- src/components/operatorsList.tsx
- src/pages/operators.tsx
> AddViewControlToPagesMissingIt

- src/components/fundsInStake.tsx
- src/components/operatorsCards.tsx
- src/components/operatorsTotal.tsx
- src/constants/index.ts
- src/hooks/useOrderedOperators.ts
- Fix nominators total when visiting the details of a specific operator
- Add possibility to order by nominator count
- Fix `i` Funds in Stake tooltip
- Add nominator count on cards
> fix nominator total

- src/components/layout.tsx
- src/components/viewSelector.tsx
- src/pages/stats.tsx
- src/states/view.ts
- Force switch to mobile view and grid view on mobile
- Cleanup some of the code in mobile layout
- Improve the view selector component for mobile
> Force grid view on mobile

- src/components/actions.tsx
- src/constants/index.ts
Thank you for the suggestion @tradebigshort
> Improve dropdown menu safety by color coding and reorganizing options

- src/components/actions.tsx
- src/hooks/useManage.ts
- src/hooks/useRegister.ts
- src/states/manage.ts
- src/states/registration.ts
- src/utils/index.ts
- Wrap functions that get triggered on input onChange in a try/catch to handle error with a toast instead to let un-handle error pop up with the ugly next error
- Add support for decimal amount
> Errors not handled on the amount input

- README.md
- Add list of env
- Add screenshot and link to live version
- Add 1-click deployment
> Improve readme and add netlify deployment badge

- src/hooks/useConnect.ts
- src/hooks/useManage.ts
- src/hooks/useRegister.ts
> add console.error to help troubleshoot and toast when detecting multiple wallet extensions

- src/components/actions.tsx
- src/components/fundsInStake.tsx
- src/components/intro.tsx
- src/components/layout.tsx
- src/components/nominatorsList.tsx
- src/components/operatorsCards.tsx
- src/components/operatorsList.tsx
- src/components/operatorsTotal.tsx
- src/components/transactionsSpotter.tsx
- src/components/wallet.tsx
- src/components/walletDetails.tsx
- src/hooks/useConnect.ts
- src/hooks/useManage.ts
- src/hooks/useOnchainData.ts
- src/hooks/useRegister.ts
- src/hooks/useTotal.ts
- src/hooks/useTx.tsx
- src/hooks/useWallet.ts
- src/pages/index.tsx
- src/pages/manage.tsx
- src/pages/register.tsx
- Standardize how states hooks are used
> Clean and simplify code

- src/hooks/useManage.ts
The current logic was using the current total stake of the operator, now it's calculating the amount stake of the user (nominator)
> fix max amount to withdraw
